name: Kubernetes Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image-tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: staging
      url: https://staging.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify cluster connection
        run: kubectl cluster-info

      - name: Create namespace if not exists
        run: |
          kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          # Update image in deployment
          kubectl set image deployment/app \
            app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image-tag }} \
            -n staging

          # Alternative: Apply manifests
          # envsubst < k8s/deployment.yaml | kubectl apply -f - -n staging

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/app -n staging --timeout=5m

      - name: Verify deployment
        run: |
          kubectl get pods -n staging
          kubectl get services -n staging

      - name: Run smoke tests
        run: |
          # Get service URL
          SERVICE_URL=$(kubectl get svc app -n staging -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

          # Wait for service to be ready
          sleep 10

          # Run health check
          curl -f http://$SERVICE_URL/health || exit 1

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-and-push, deploy-staging]
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_PRODUCTION }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify cluster connection
        run: kubectl cluster-info

      - name: Create namespace if not exists
        run: |
          kubectl create namespace production --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy with canary strategy
        run: |
          # Deploy canary version (10% traffic)
          kubectl set image deployment/app-canary \
            app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image-tag }} \
            -n production

          # Wait for canary rollout
          kubectl rollout status deployment/app-canary -n production --timeout=3m

      - name: Monitor canary metrics
        run: |
          echo "Monitoring canary deployment for 2 minutes..."
          sleep 120

          # Check for errors (this is a placeholder - integrate with your monitoring)
          ERROR_RATE=$(kubectl logs -l app=app-canary -n production --tail=100 | grep -c "ERROR" || true)

          if [ $ERROR_RATE -gt 10 ]; then
            echo "High error rate detected in canary deployment"
            exit 1
          fi

      - name: Promote canary to production
        run: |
          # Update main deployment
          kubectl set image deployment/app \
            app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image-tag }} \
            -n production

          # Wait for rollout
          kubectl rollout status deployment/app -n production --timeout=5m

      - name: Verify production deployment
        run: |
          kubectl get pods -n production
          kubectl get services -n production

      - name: Run production smoke tests
        run: |
          SERVICE_URL=$(kubectl get svc app -n production -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

          # Health check
          curl -f http://$SERVICE_URL/health || exit 1

          # API check
          curl -f http://$SERVICE_URL/api/users || exit 1

      - name: Cleanup canary deployment
        if: success()
        run: |
          kubectl scale deployment/app-canary --replicas=0 -n production

  rollback:
    name: Rollback Deployment
    runs-on: ubuntu-latest
    if: failure()
    needs: [deploy-production]

    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_PRODUCTION }}" | base64 -d > $HOME/.kube/config

      - name: Rollback deployment
        run: |
          kubectl rollout undo deployment/app -n production
          kubectl rollout status deployment/app -n production

      - name: Notify team
        run: |
          echo "Deployment rolled back due to failure"
          # Add notification logic here (Slack, email, etc.)
